home/urls.py
from django.urls import path,include
from . import views
app_name='home'
urlpatterns = [

    # path('', views.home,name='home'),
    path('',views.Home.as_view(),name='index'),
    # path('<int:pk>/', views.Detail.as_view(), name='detail'),
    path('<int:pk>/',views.detail,name='detail'),
    path('booking/<int:id>/', views.booking, name='booking'),
    path('checkout/<visitor_name>/<phone_number>/<platinum_seats>/<gold_seats>/<silver_seats>/<total_platinum_price>/<total_gold_price>/<total_silver_price>/<net_price>/<booked_date>/',views.checkout,name='checkout'),
    path('search/',views.search,name='search'),
    path('check_avai/<int:id>/',views.check_avai,name='check_avai')

]

movie_booking/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Event(models.Model):
    city = models.CharField(max_length=200, default='')
    venuname = models.CharField(max_length=200, help_text='add venue name', default='')
    name = models.CharField(max_length=200,default='',verbose_name='parking place')
    discription = models.TextField(default='')
    slug = models.SlugField(unique=True)
    platinum_seats = models.IntegerField(default=0)
    gold_seats = models.IntegerField(default=0)
    silver_seats = models.IntegerField(default=0)
    platinum_price = models.IntegerField(default=0)
    gold_price = models.IntegerField(default=0)
    silver_price = models.IntegerField(default=0)
    last_date=models.DateField(default=timezone.now)
    image = models.FileField(upload_to='home/movies/')
    timestamp=models.DateField(default=timezone.now )

    class Meta:
        unique_together = ('slug','name')
        verbose_name='parking'
        

    def __str__(self):
        return self.name

class Booking(models.Model):
    visitor_name=models.CharField(max_length=200,default='')
    phone_number=models.IntegerField(default=0)
    event_name=models.CharField(max_length=200,default='')
    platinum_seats = models.IntegerField(default=0)
    gold_seats = models.IntegerField(default=0)
    silver_seats = models.IntegerField(default=0)
    time_choice=(
        ('Moring 10-12','Moring 10-12'),
        ('12-2 ','12-2'),
        ('2-4','2-4'),
        ('4-6','4-6'),
        ('6-8','6-8'),        
        ('night 8-10','night 8-10'),
    )

    time_preference=models.CharField(max_length=20,choices=time_choice,default=0)
    booking_date=models.DateField(default=timezone.now)

    def __str__(self):
        return self.visitor_name


# class BookinValidation(models.Model):
#     visitor_name=models.CharField(max_length=200,default='')
#     phone_number = models.IntegerField(default=0)
#     time_preference = models.CharField(max_length=10, default=0)
#     platinum_seats = models.IntegerField(default=0)
#     gold_seats = models.IntegerField(default=0)
#     silver_seats = models.IntegerField(default=0)
#     booked_date=models.DateField(default=timezone.now)
#
#     def __str__(self):
#         return self.visitor_name
#
#

home/forms.py
from django.forms import ModelForm,DateField,Textarea,TextInput,Select
from .models import  Booking
class BookingForm(ModelForm):

    class Meta:
        model=Booking
        fields=['visitor_name','phone_number','event_name','time_preference','platinum_seats','gold_seats','silver_seats' ,'booking_date']
        widgets={
            'booking_date':TextInput(attrs={'type':'date','class':'form-control','type':'hidden'}),
            'visitor_name':TextInput(attrs={'class':'form-control'}),
            'phone_number':TextInput(attrs={'class':'form-control'}),
            'event_name':TextInput(attrs={'class':'form-control'}),
            'time_preference':Select(attrs={'class':'form-control'}),
            'platinum_seats':TextInput(attrs={'class':'form-control'}),
            'gold_seats':TextInput(attrs={'class':'form-control'}),
            'silver_seats':TextInput(attrs={'class':'form-control'}),
            'event_name':TextInput(attrs={'type':'hidden'})
            }

home/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages


from .forms import BookingForm
from .models import Event,Booking
# Create your views here.
# def home(request):
#     events=Event.objects.all()
#     return  HttpResponse('nameste admin')

class Home(generic.ListView):
    template_name = 'home/index.html'
    context_object_name = 'events'

    def get_queryset(self):
        return Event.objects.all()

# class Detail(generic.DetailView):
#     model = Event
#     template_name = 'home/detail.html'

def detail(request,pk):
    object=Event.objects.get(pk=pk)
    form=BookingForm

    return render(request,'home/detail.html',{'object':object,'form':form})


def check_avai(request,id):
    object = Event.objects.get(id=id)
    total_paltinum_seats = object.platinum_seats
    total_gold_seats = object.gold_seats
    total_silver_seats = object.silver_seats
    last_date=object.last_date


    check_total_platinum_seats=0
    check_total_gold_seats=0
    check_total_silver_seats=0
    
    time_preference=request.POST.get('time_preference')
    booking_date=request.POST.get('booking_date')
    event_name=request.POST.get('event_name')
    for_same_date=Booking.objects.filter(booking_date=booking_date)
    for_same_event_name=for_same_date.filter(event_name=event_name)
    for_same_time_preference=for_same_event_name.filter(time_preference=time_preference)

    for i in for_same_time_preference:
        check_total_platinum_seats += i.platinum_seats
        check_total_gold_seats += i.gold_seats
        check_total_silver_seats += i.silver_seats

    message=''
    if check_total_platinum_seats < total_paltinum_seats:
        rest_platinum_seats = total_paltinum_seats - check_total_platinum_seats
        message += f'paltinum_seats:{rest_platinum_seats},'
    else:
        message += 'No Platinum Seats Avaiable for your given Requirement '

    if check_total_gold_seats < total_gold_seats:
        rest_gold_seats = total_gold_seats - check_total_gold_seats
        message += f'Gold seats:{rest_gold_seats},'
    else:
        message += 'No Gold Seats Avaiable for your given Requirement'

    if check_total_silver_seats < total_silver_seats:
        rest_silver_seats = total_silver_seats - check_total_silver_seats
        message += f'Silver seats:{rest_silver_seats},'
    else:
        message += 'No Silver Seats Avaiable for your given Requirement'

    if str(booking_date)>str(last_date):
        message='This Show is not Avaiable for your given date'

    messages.info(request, message)
    return render(request,'home/detail.html',{'object':object,'time_preference':time_preference,'booking_date':booking_date})
   

def booking(request,id):
    id=id
    form = BookingForm
    # TAKING TOTAL NUMBER OF SEATS FROM EVENT MODEL
    seats = Event.objects.get(id=id)
    total_paltinum_seats = seats.platinum_seats
    total_gold_seats = seats.gold_seats
    total_silver_seats= seats.silver_seats
    name=seats.name
    
    if request.method=='POST':
        id=id
        form=BookingForm(request.POST)
        if form.is_valid():         
            visitor_name=form.cleaned_data['visitor_name']
            phone_number=form.cleaned_data['phone_number']
            time_preference = form.cleaned_data['time_preference']
            paltinum_seats = form.cleaned_data['platinum_seats']
            gold_seats = form.cleaned_data['gold_seats']
            silver_seats = form.cleaned_data['silver_seats']
            booking_date = form.cleaned_data['booking_date']
            event_name=form.cleaned_data['event_name']

            print(paltinum_seats)

            get_price=Event.objects.filter(id=id)
            for i in get_price:
                platinum_price = i.platinum_price
                gold_price = i.gold_price
                silver_price = i.silver_price
                

            message=''
            check_total_platinum_seats=0
            check_total_gold_seats=0
            check_total_silver_seats=0

           

            for_same_date=Booking.objects.filter(booking_date=booking_date)
            for_same_event_name=for_same_date.filter(event_name=event_name)
            for_same_time_preference=for_same_event_name.filter(time_preference=time_preference)

            


            for i in for_same_time_preference:
                check_total_platinum_seats+=i.platinum_seats
                check_total_gold_seats+=i.gold_seats
                check_total_silver_seats+=i.silver_seats



            if check_total_platinum_seats<total_paltinum_seats:
                rest_platinum_seats=total_paltinum_seats-check_total_platinum_seats
                message+=f'paltinum_seats:{rest_platinum_seats},'
            else:
                message+='No Platinum Seats Avaiable for your given Requirement '

            if check_total_gold_seats<total_gold_seats:
                rest_gold_seats=total_gold_seats-check_total_gold_seats
                message+=f'Gold seats:{rest_gold_seats},'
            else:
                message+='No Gold Seats Avaiable for your given Requirement'

            if check_total_silver_seats<total_silver_seats:
                rest_silver_seats=total_silver_seats-check_total_silver_seats
                message+=f'Silver seats:{rest_silver_seats},'
            else:
                message+='No Silver Seats Avaiable for your given Requirement'


            
            check_total_platinum_seats+=paltinum_seats
            check_total_gold_seats+=gold_seats
            check_total_silver_seats+=silver_seats

            message+=f'Please  try to change the time slot for the same day booking and  for same seat type '




            if check_total_platinum_seats<total_paltinum_seats and check_total_gold_seats<total_gold_seats and check_total_silver_seats<total_silver_seats:
                message='your booking is done !thanks for using us visit again!'
                data=form.save()
                platinum_seats=data.platinum_seats
                gold_seats=data.gold_seats
                silver_seats=data.silver_seats
                visitor_name=data.visitor_name
                phone_number=data.phone_number
                total_platinum_price=platinum_seats*platinum_price
                total_gold_price=gold_seats*gold_price
                total_silver_price=silver_seats*silver_price
                booked_date=data.booking_date

                net_price=total_platinum_price+total_gold_price+total_silver_price

                messages.info(request, message)
                return HttpResponseRedirect(reverse('home:checkout',args=(visitor_name,phone_number,platinum_seats,gold_seats,silver_seats, total_platinum_price, total_gold_price,total_silver_price,net_price,booked_date)))

            messages.info(request,message)
            return HttpResponseRedirect(reverse('home:booking',args=(id,)))

        else:
            return HttpResponse('somthing went wrong',form.errors)

    return render(request,'home/booking.html',{'form':form,'id':id,'name':name})

def checkout(request,visitor_name,phone_number,platinum_seats,gold_seats,silver_seats, total_platinum_price, total_gold_price,total_silver_price,net_price,booked_date):
    return  render(request,'home/checkout.html',{'visitor_name':visitor_name,
             'phone_number':phone_number,
             'platinum_seats':platinum_seats,
             'gold_seats':gold_seats,
             'silver_seats':silver_seats,
             'total_platinum_price':total_platinum_price,
             'total_gold_price':total_gold_price,
             'total_silver_price':total_silver_price,
             'net_price':net_price,
             'booked_date':booked_date
             })


def search(request):
    searched=request.GET.get('q')
    # return HttpResponse('hello i am searched',searched)
    name=Event.objects.filter(name__contains=searched)
    city=Event.objects.filter(city__contains=searched)
    return render(request, 'home/search.html', {'name': name,'city':city})

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
    <style>
        .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
}
 .box-shadow:hover {
  box-shadow: 0 5px 15px 2px rgba(0, 0, 0, 0.1);
}
body{
  background: yellow;
}
    </style>
  </head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      

    </ul>
    <form class="form-inline my-4 my-lg-0" method="get" action="{% url 'home:search' %}">
      <input class="form-control mr-sm-4" name="q" type="search" placeholder="City/Show" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


{% block body %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/booking.html
{% extends 'home/base.html' %}
{% block body %}
<div class ="container">
{% include 'home/messages.html ' %}
{% load crispy_forms_tags %}


    <form action="{% url 'home:booking' id  %}" method="post">
         {% csrf_token %}
   
<div id="div_id_visitor_name" class="control-group"> <label for="id_visitor_name" class="control-label requiredField">
                Visitor name<span class="asteriskField">*</span> </label> <div class="controls"> <input type="text" name="visitor_name" class="form-control textinput textInput" maxlength="200" required id="id_visitor_name"> </div> </div> <div id="div_id_phone_number" class="control-group"> <label for="id_phone_number" class="control-label requiredField">
                Phone number<span class="asteriskField">*</span> </label> <div class="controls"> <input type="text" name="phone_number" value="0" class="form-control textinput textInput" required id="id_phone_number"> </div> </div> <input type="hidden" name="event_name" id="id_event_name"> <div id="div_id_time_preference" class="control-group"> <label for="id_time_preference" class="control-label requiredField">
                <span class="asteriskField">*</span> </label> <div class="controls"> <select hidden name="time_preference" class="form-control select" id="id_time_preference"> <option value="Moring 9-12">Moring 9-12</option> <option value="12-3 ">12-3</option> <option value="3-6">3-6</option> <option value="6-9">6-9</option> <option value="night 9-12">night 9-12</option>

</select> </div> </div> <div id="div_id_platinum_seats" class="control-group"> <label for="id_platinum_seats" class="control-label requiredField">
                Platinum seats<span class="asteriskField">*</span> </label> <div class="controls"> <input type="text" name="platinum_seats" value="0" class="form-control textinput textInput" required id="id_platinum_seats"> </div> </div> <div id="div_id_gold_seats" class="control-group"> <label for="id_gold_seats" class="control-label requiredField">
                Gold seats<span class="asteriskField">*</span> </label> <div class="controls"> <input type="text" name="gold_seats" value="0" class="form-control textinput textInput" required id="id_gold_seats"> </div> </div> <div id="div_id_silver_seats" class="control-group"> <label for="id_silver_seats" class="control-label requiredField">
                Silver seats<span class="asteriskField">*</span> </label> <div class="controls"> <input type="text" name="silver_seats" value="0" class="form-control textinput textInput" required id="id_silver_seats"> </div> </div> <input type="hidden" name="booking_date" value="2019-03-08 11:09:47.762582+00:00" class="form-control" id="id_booking_date"><input type="hidden" name="initial-booking_date" value="2019-03-08 11:09:47.762582+00:00" id="initial-id_booking_date">


    <br>
    <input  class ="btn btn-primary " type="submit" value="submit">
</form>

</div>
<script type="text/javascript">
    document.getElementById('id_event_name').setAttribute("value","{{name}}");

    time_preference=sessionStorage.getItem("time");
    date=sessionStorage.getItem("date");
    document.getElementById('id_booking_date').setAttribute("value",date);
    var e=document.getElementById('id_time_preference');
    ind=e.options[e.selectedIndex];
    ind.value=time_preference;
    ind.innerHTML=time_preference;
    




</script>
 

{% endblock %}

home/templates/home/checkout.html
{% extends 'home/base.html' %}
{% block body %}
<div class ="container">
{% include 'home/messages.html ' %}

    <h1>namaste checkout page </h1>


    <table class="table">

            <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Phone</th>
              <th scope="col">Platinum seats</th>
              <th scope="col">Gold seats</th>
              <th scope="col">Silver Seats</th>
              <th scope="col">Platinum total</th>
              <th scope="col">Gold total</th>
              <th scope="col">Silver total</th>
              <th scope="col">Booking date</th>
              <th scope="col">Total</th>
            </tr>
           </thead>


           <tbody>
           <tr>
               <th scope="col">{{visitor_name}}</th>
               <th scope="col">{{phone_number}}</th>
               <th scope="col">{{platinum_seats}}</th>
               <th scope="col">{{gold_seats}}</th>
               <th scope="col">{{silver_seats}}</th>
               <th scope="col">{{total_platinum_price}}</th>
               <th scope="col">{{total_gold_price}}</th>
               <th scope="col">{{total_silver_price}}</th>
               <th scope="col">{{booked_date}}</th>
               <th scope="col">{{net_price}}</th>




           </tr>

           </tbody>
    </table>
</div>
{% endblock %}

home/templates/home/detail.html
{% extends 'home/base.html' %}
{% block body %}



<div class="row">
  <div class="col md-4 ">
    <div class="card" style="width: 18rem;">
      <img src="{{object.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{object.name}}</h5>
        <p class="card-text">{{object.discription|slice:"0:200"}}</p>
        <p class="card-text"><b>Last Date for booking:{{object.last_date}}</b></p>
        <a href="{% url 'home:booking' object.id  %}" class="btn btn-primary">Book</a>
      </div>
    </div>
  </div>

  <div class="col md-8">



  <form action="{% url  'home:check_avai' object.id   %}" method="post">
    {% csrf_token %}
     <div style="padding: 20px" id="div_id_time_preference" class="control-group"> <label for="id_time_preference" class="control-label requiredField">
    Time preference<span class="asteriskField">*</span> </label> <div class="controls"> <select   name="time_preference" class="form-control select" id="id_time_preference" > 
      
    <option value="Moring 10-12">Moring 10-12</option>

  <option value="12-2 ">12-2</option>

  <option value="2-4">2-4</option>

  <option value="4-6">4-6</option>

  <option value="6-8">6-8</option>

  <option value="night 8-10">night 8-10</option>

    </select>
    <br><br>





    <input type="hidden" name="event_name" id="id_event_name">
    <div id="div_id_booking_date" class="control-group"> <label for="id_booking_date" class="control-label requiredField">
      Booking date<span class="asteriskField">*</span> </label> <div class="controls"> <input type="date" name="booking_date" value="" class="form-control textinput textInput" required id="id_booking_date">


    </div><br> 
    <input type="submit" onclick="get_user_input();"  class="btn btn-primary" name="" value="Check Avaiabilty">
  </div>
  </form>
  {% include 'home/messages.html ' %}
</div>
<script type="text/javascript">
     date=sessionStorage.getItem("date");
     
    document.getElementById('id_event_name').setAttribute("value","{{object}}");
    document.getElementById('id_booking_date').setAttribute("value",date);
    time=sessionStorage.getItem("time");
    document.getElementById('o1').setAttribute("value",time);
    document.getElementById('o1').innerHTML=time

  


    




    function get_user_input(){
      get_time_pref=document.getElementById('id_time_preference').value;
      get_date=document.getElementById('id_booking_date').value;
      time=sessionStorage.setItem("time",get_time_pref);
      date=sessionStorage.setItem("date",get_date);
      document.getElementById('id_booking_date').setAttribute("value",date);
    }
    
</script>
    


{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block body %}
<div class="row">

{% for event in events %}

    <div class="col md-6">
        <div class="card box-shadow" style="width: 18rem;">
  <img src="{{event.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{event.name}}</h5>
    <h5 class="card-title">{{event.city}},{{event.venuname}}</h5>
    <!-- <h5 class="card-title">{{event.venuname}}</h5> -->
    <p class="card-text">{{event.discription|slice:"0:50"}}....</p>
    <a href="{% url 'home:detail' event.id %}" class="btn btn-primary">View</a>
  </div>
</div>
    </div>
{% endfor %}
    </div>
{% endblock %}

home/templates/home/messages.html
{% if messages %}
    {%  for message in messages %}
        {% if message.tags == 'info' %}
             <br>
             <div class="alert alert-primary" role="alert">
  {{message}}
</div>
        {% endif %}


    {% endfor %}
{%  endif %}

<script type="text/javascript">
	
</script>

home/templates/home/search.html
{% extends 'home/base.html' %}
{% block body %}
<div class ="container">
<div class="row">

{% for event in name %}

    <div class="col md-6">
        <div class="card" style="width: 18rem;">
  <img src="{{event.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{event.name}}</h5>
    <p class="card-text">{{event.discription|slice:"0:50"}}....</p>
    <a href="{% url 'home:detail' event.id %}" class="btn btn-primary">View</a>
  </div>
</div>
    </div>
{% endfor %}

    {% for event in city %}

    <div class="col md-6">
        <div class="card" style="width: 18rem;">
  <img src="{{event.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{event.name}}</h5>
    <p class="card-text">{{event.discription|slice:"0:50"}}....</p>
    <a href="{% url 'home:detail' event.id %}" class="btn btn-primary">View</a>
  </div>
</div>
    </div>
{% endfor %}


    </div>

</div>
{% endblock %}